package com.thesis.sportologia.ui.entities

const val REFRESH_SERVICES_LIST_KEY = "REFRESH_SERVICES_LIST_KEY"
const val REFRESH_POSTS_LIST_KEY = "REFRESH_POSTS_LIST_KEY"
const val REFRESH_EVENTS_LIST_KEY = "REFRESH_EVENTS_LIST_KEY"